### ISSUE TITLE
APIs Documentation

### ISSUE THREAD

**Issue by jerome-lecorvaisier** [yulPa/yulMails#6]
You might be interested to check Swagger to document APIs.

> Swagger is the world’s largest framework of API developer tools for the OpenAPI Specification(OAS), enabling development across the entire API lifecycle, from design and documentation, to test and deployment.

[https://swagger.io/](https://swagger.io/ )

You can see here what it looks like [http://petstore.swagger.io/](http://petstore.swagger.io/)

**Comment by tormath1** [comment]
Oh ! Awesome swag. And we could host on a `github.io` domain ?

**Comment by AurelienPONCINI** [comment]
yeap ;) possible normalement si tu met dans /docs

**Comment by tormath1** [comment]
Yesterday, I tried out swagger generation with `gRPC` and this is pretty awesome. With a simple `proto buffer` file: 

```proto
syntax="proto3";
package echo;
import "google/api/annotations.proto";

message EchoMessage {
  string value = 1;
}

service EchoService {
  rpc Echo (EchoMessage) returns (EchoMessage) {
    option (google.api.http) = {
      post: "/v1/echo"
      body: "*"
    };
  }
}
```

I generated my `go` cobase in order to implement this function `echo` in a few lines and I was able to generate this: 
![image](https://user-images.githubusercontent.com/28657343/35193472-0f13e2c4-fea3-11e7-8564-afe21c701192.png)

What I say: refactor our few APIs already presents and use this [article](https://coreos.com/blog/grpc-protobufs-swagger.html) in order to provide a gRPC / HTTP1.1 compatibility.

**Comment by tormath1** [comment]
FYI, swagger API is generated from go comments: https://github.com/yulPa/yulmails/tree/master/api/docs
